### ISSUE TITLE
OpenGL does not expose all uniform functionality.

### ISSUE THREAD

**Issue by dharaj** [haskell-opengl/OpenGL#14]
Sometimes I want to use glUniform*, but the OpenGL UniformLocation type does not work with it. I have to unsafeCoerce it to the underlying GLint and use that. If the OpenGL API exposed all the uniform api, it wouldn't be an issue.

To be honest, I think OpenGL might be built too far above the raw bindings. Maybe it should just add type discipline to the GLRaw functions.

**Comment by svenpanne** [comment]
The matrix part has been added in b1b50031f7880b918fc6ec056342c5c89f118213, I'm about to make a new release on Hackage.

Samplers are already supported (`TextureUnit` is an instance of `Uniform`), and you can pass image uniforms via the `GLint` instance, so I think all necessary functionality is exposed.
