### ISSUE TITLE
Fix typo: SeperateAttribs -> SeparateAttribs

### ISSUE THREAD

**Issue by kranich** [haskell-opengl/OpenGL#77]
I submitted a pull request #76 to that end.

**Comment by svenpanne** [comment]
To make the transition a bit smoother and avoid a major version bump, can we please keep the old `SeperateAttribs` constructor, too? Just add the correctly spelled constructor and a deprecation pragma like:

    {-# DEPRECATED SeperateAttribs "Use 'SeparateAttribs' instead." #-}

After a few releases I'll remove the old constructor and bump the major version then. GLUT had a similar issue, BTW: https://github.com/haskell-opengl/GLUT/commit/3e4baea50971af2bd21febbc8e70356113aeecb8

**Comment by kranich** [comment]
OK, just implemented your suggestions.

**Comment by kranich** [comment]
Build passed. You can merge pull request #76.

**Comment by svenpanne** [comment]
Done. Thanks for the fix!
