### ISSUE TITLE
OpenGL addition in Stackage

### ISSUE THREAD

**Issue by rvion** [haskell-opengl/OpenGL#79]
Hello, could openGL be added on stackage, with GLURaw, GLUT, OpenGLRaw, StateVar ?

**Comment by rvion** [comment]
I made a PR to ease addition in stackage in case you would like to do so.
If you don't, no prob, I'll just close it.

Anyway, thanks for all the good work :)

/cc  @dagit @elliottt @jmcarthur @svenpanne

**Comment by svenpanne** [comment]
I think we can close this issue, the real discussion is going on at fpco/stackage#774. If there is something to do on the `OpenGL` package side, feel free to re-open...

**Comment by rvion** [comment]
yep, thanks
