### ISSUE TITLE
GL_DEPTH24_STENCIL8 is missing from PixelInternalFormat

### ISSUE THREAD

**Issue by KaneTW** [haskell-opengl/OpenGL#84]

**Comment by svenpanne** [comment]
I just had a quick look, and it seems that a few more internal formats from more recent OpenGL revisions are missing. I'll add them after a more thorough  review...

Thanks for pointing that out! :-)

**Comment by svenpanne** [comment]
I've uploaded a new version 3.0.2.0 to Hackage, containing the missing format plus some more format-related stuff.
