### ISSUE TITLE
glEnable/glDisable for GL_DEPTH_TEST is not exposed

### ISSUE THREAD

**Issue by KaneTW** [haskell-opengl/OpenGL#85]

**Comment by svenpanne** [comment]
Actually it is exposed, perhaps not in the way you expected it, see http://hackage.haskell.org/package/OpenGL-3.0.1.0/docs/Graphics-Rendering-OpenGL-GL-PerFragment.html#g:7. ``depthFunc $= Nothing`` disables the depth test, ``depthFunc $= Just Less`` enables it with "less" as the comparison function, etc.
